---
# cPanel Git Deployment for Kadesh (SPA + PHP backend)
# This deployment copies ONLY the `public/` folder to the subdomain's docroot.
# It does NOT run Composer, Artisan, or Node builds on the server.
# Ensure the repository already contains production-ready files in `public/`.

deployment:
  tasks:
    - /bin/echo "[Kadesh] Deploy started at $(/bin/date)"
    - export DOCROOT="/home/mmbsites/public_html/kadesh"
    - /bin/mkdir -p "$DOCROOT"
    # Sync public/ to docroot (delete removed files to avoid stale assets)
  - /bin/rsync -a --delete --exclude=.htaccess public/ "$DOCROOT/"
    # Optional hardening permissions
    - /bin/find "$DOCROOT" -type d -exec /bin/chmod 755 {} \;
    - /bin/find "$DOCROOT" -type f -exec /bin/chmod 644 {} \;
    - /bin/echo "[Kadesh] Deploy finished at $(/bin/date)"