---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mmbsites/public_html/kadesh
    - mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH
    - cp .env.cpanel .env
    - composer install --optimize-autoloader --no-dev --no-interaction
    - php artisan key:generate --force
    - php artisan config:clear
    - php artisan route:clear  
    - php artisan view:clear
    - php artisan cache:clear
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - npm ci --production
    - npm run build
    - chmod -R 755 storage
    - chmod -R 755 bootstrap/cache
    - composer dump-autoload --optimize
    - php artisan storage:link